version: '3.9'

services:
  grafana:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: grafana-development
    restart: unless-stopped
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - GF_DEFAULT_INSTANCE_NAME=my-instance
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_LOG_MODE=console
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - regenfass

networks:
  regenfass:
    name: regenfass
    driver: bridge
